const mongoose = require("mongoose");

// ── Single message within a conversation ──
const messageSchema = new mongoose.Schema({
    role: {
        type: String,
        enum: ["user", "bot"],
        required: true
    },
    text: {
        type: String,
        required: true,
        maxLength: 5000
    },
    timestamp: {
        type: Date,
        default: Date.now
    }
});

// Full conversation (one session = one document) 
const conversationSchema = new mongoose.Schema({

    // Which website owner this conversation belongs to
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "user",
        required: true,
        index: true          // indexed we query by userId constantly
    },

    // Unique ID for this chat session (generated by widget)
    sessionId: {
        type: String,
        required: true,
        unique: true,
        index: true
    },

    // Anonymous visitor identifier (fingerprint from widget)
    visitorId: {
        type: String,
        default: "anonymous"
    },

    // The page URL where the conversation started
    page: {
        type: String,
        default: ""
    },

    // All messages in this conversation
    messages: {
        type: [messageSchema],
        default: []
    },

    // Quick count — avoids loading all messages just to count
    messageCount: {
        type: Number,
        default: 0
    },

    // How long the session lasted in seconds
    duration: {
        type: Number,
        default: 0
    },

    // Visitor satisfaction (collected at end of chat)
    satisfaction: {
        type: String,
        enum: ["positive", "negative", "neutral", null],
        default: null
    },

    // active = still chatting | ended = session closed
    status: {
        type: String,
        enum: ["active", "ended"],
        default: "active"
    },

    // Gemini tokens used across this conversation (for cost tracking)
    totalTokensUsed: {
        type: Number,
        default: 0
    },

}, { timestamps: true });  // adds createdAt + updatedAt automatically


// ── Index for analytics queries ──
// When dashboard loads analytics, we query: userId + date range
conversationSchema.index({ userId: 1, createdAt: -1 });


module.exports = mongoose.model("conversation", conversationSchema);